routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('outbox', 'OutboxController')->names('outbox');
});

app/Outbox.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Outbox extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'index',
        'suffix',
        'reff',
        'date',
        'subject',
        'destination',
        'document',
        'category_id',
        'user_id',
    ];


    /**
     * Get the category associated with the Outbox
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function category()
    {
        return $this->hasOne(Category::class, 'id', 'category_id');
    }

    /**
     * Get the user associated with the Outbox
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }
}

app/Http/Controllers/OutboxController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CreateOutboxRequest;
use App\Http\Requests\UpdateOutboxRequest;
use App\Outbox;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class OutboxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            $query = Outbox::query();

            return DataTables::of($query)
                ->editColumn('date', function ($item) {
                    return  date('d-m-Y', strtotime($item->date));
                })
                ->editColumn('document', function ($item) {
                    if ($item->document) {
                        return  '<a href="' . Storage::url($item->document) . '" target="_blank" class="btn btn-light text-danger" title="Lihat"><i class="fas fa-file-pdf"></i></a>';
                    } else {
                        return '';
                    }
                })
                ->addColumn('category', function ($item) {
                    return $item->category->code . " " . $item->category->name;
                })
                ->addColumn('action', function ($item) {
                    $action = '';

                    if (Auth::id() == $item->user_id) {
                        $action .=
                            '<a href="' . route('outbox.edit', $item->id) . '" class="btn btn-light" title="Edit"><i class="fas fa-pencil-alt"></i></a>';
                    }

                    $action .= '<a href="' . route('outbox.show', $item->id) . '" class="btn btn-light" title="Detail"><i class="fas fa-chevron-right"></i></a>';

                    return '<div class="btn-group" role="group">' . $action . '</div>';
                })
                ->rawColumns(['document', 'action'])
                ->make(true);
        }

        return view('pages.outbox.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.outbox.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateOutboxRequest $request)
    {
        $data = $request->all();

        $today = Carbon::now()->startOfDay();
        $date = Carbon::parse($data['date']);
        $suffix = null;

        if ($date->lt($today)) {
            $last_index = Outbox::where('date', '<=', $date->format('Y-m-d'))
                ->whereYear('date', $date->year)
                ->orderBy('index', 'desc')
                ->orderBy('suffix', 'desc')
                ->first();

            if (!$last_index) {
                $last_index = Outbox::whereYear('date', $date->year)
                    ->orderBy('index', 'asc')
                    ->orderBy('suffix', 'desc')
                    ->first();
            }

            $next_index = $last_index ? $last_index->index : 1;

            if ($last_index && $last_index->suffix) {
                $suffix = Str::upper(++$last_index->suffix);
            } else if ($last_index) {
                $suffix = 'A';
            }
        } else {
            $last_index = Outbox::whereYear('date', $date->year)->orderBy('index', 'desc')->first();
            $next_index = $last_index ? $last_index->index + 1 : 1;
        }

        $category = Category::findOrFail($data['category_id']);

        $data['suffix'] = $suffix;
        $data['reff'] = "W28-A4/" . $next_index . $suffix . "/" . $category->code . "/" . romanic_number($date->month) . "/" . $date->year;
        $data['date'] = $date->format('Y-m-d');
        $data['index'] = $next_index;
        $data['user_id'] = Auth::id();

        $outbox = Outbox::create($data);

        return redirect()->route('outbox.edit', $outbox->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Outbox  $outbox
     * @return \Illuminate\Http\Response
     */
    public function show(Outbox $outbox)
    {
        return view('pages.outbox.show', [
            'data' => $outbox
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Outbox  $outbox
     * @return \Illuminate\Http\Response
     */
    public function edit(Outbox $outbox)
    {
        $outbox = Outbox::with('category')->findOrFail($outbox->id);

        $today = Carbon::now()->startOfDay();
        $date = Carbon::parse($outbox->date);

        $editableDate = $today->lte($date);

        if (Auth::id() == $outbox->user_id) {
            return view('pages.outbox.edit', [
                'data' => $outbox,
                'editableDate' => $editableDate
            ]);
        }

        return view('pages.outbox.show', [
            'data' => $outbox
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Outbox  $outbox
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateOutboxRequest $request, Outbox $outbox)
    {
        $data = $request->all();

        $today = Carbon::now()->startOfDay();
        $date = Carbon::parse($data['date']);

        $category = Category::findOrFail($data['category_id']);

        if ($date->format('Y-m-d') == $outbox->date) {
            $data['reff'] = "W28-A4/" . $outbox->index . $outbox->suffix . "/" . $category->code . "/" . romanic_number($date->month) . "/" . $date->year;
        } else {
            $suffix = null;

            if ($date->lt($today)) {

                $last_index = Outbox::where('date', '<=', $date->format('Y-m-d'))
                    ->where('id', '<>', $outbox->id)
                    ->whereYear('date', $date->year)
                    ->orderBy('index', 'desc')
                    ->orderBy('suffix', 'desc')
                    ->first();

                if (!$last_index) {
                    $last_index = Outbox::whereYear('date', $date->year)
                        ->where('id', '<>', $outbox->id)
                        ->orderBy('index', 'asc')
                        ->orderBy('suffix', 'desc')
                        ->first();
                }

                $next_index = $last_index ? $last_index->index : 1;

                if ($last_index && $last_index->suffix) {
                    $suffix = Str::upper(++$last_index->suffix);
                } else if ($last_index) {
                    $suffix = 'A';
                }
            } else {
                $last_index = Outbox::whereYear('date', $date->year)->orderBy('index', 'desc')->first();
                $next_index = $last_index ? $last_index->index + 1 : 1;
            }

            $data['suffix'] = $suffix;
            $data['reff'] = "W28-A4/" . $next_index . $suffix . "/" . $category->code . "/" . romanic_number($date->month) . "/" . $date->year;
            $data['index'] = $next_index;
        }

        if ($file = $request->file('document')) {

            $extention = $file->getClientOriginalExtension();

            if (in_array($extention, ['pdf'])) {
                $data['document'] = $file->store('assets/outbox', 'public');
            } else {
                return back()->withInput()->withErrors(['document' => 'Dokumen harus dalam bentuk pdf']);
            }
        }

        $data['date'] = $date->format('Y-m-d');
        $outbox->update($data);

        return redirect()->route('outbox.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Outbox  $outbox
     * @return \Illuminate\Http\Response
     */
    public function destroy(Outbox $outbox)
    {
        $outbox->delete();

        return redirect()->route('outbox.index');
    }
}

resources/views/pages/outbox/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card shadow-sm p-3">

                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4>Tambah Surat Keluar</h4>
                    </div>

                    <form action="{{ route('outbox.store') }}" class="my-4" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="date">Tanggal Surat</label>
                                    <input type="text" id="date" name="date"
                                           class="form-control datepicker @error('date') is-invalid @enderror"
                                           data-provide="datepicker"
                                           value="{{ old('date') }}">

                                    @error('date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="category_id">Kode Surat</label>
                                    <select name="category_id" id="category_id"
                                            class="form-control select2 @error('category_id') is-invalid @enderror">
                                    </select>

                                    @error('category_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="subject">Perihal</label>
                                    <input type="text" id="subject" name="subject"
                                           class="form-control @error('subject') is-invalid @enderror"
                                           value="{{ old('subject') }}">

                                    @error('subject')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="destination">Tujuan</label>
                                    <input type="text" id="destination" name="destination"
                                           class="form-control @error('destination') is-invalid @enderror"
                                           value="{{ old('destination') }}">

                                    @error('destination')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div id="card_desc" class="card bg-light my-3" style="display: none">
                                    <div class="card-body">
                                        <div id="spinner" style="display: none">
                                            <div class="justify-content-center p-3 d-flex">
                                                <div class="dot-spin"></div>
                                            </div>
                                        </div>
                                        <div id="category_desc"></div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row mt-3">
                            <div class="col">
                                <button type="submit" class="btn btn-success px-3 mr-1">Simpan</button>
                                <a href="{{ route('outbox.index') }}" class="btn btn-light px-3">Batal</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('script-after')
<script>
    $(document).ready(function(){
        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
            language: 'id',
            autoclose: true,
            todayHighlight: true,
            daysOfWeekHighlighted: [0],
        });

        $('#category_id').select2({
            ajax: {
                placeholder: '-- Pilih --',
                    dalay: 100,
                        url: '{{ route('api.category.populate') }}',
                        dataType: 'json',
                        type: 'POST',
                        data: function (params){
                        return {
                            q: params.term,
                            };
                        },
                        processResults: function (data) {
                        return {
                        results: data.items
                    };
                }
            }
        });

        $('#category_id').change(function(){
            const url = "{{ route('api.category.detail') }}";
            let id = $('#category_id').val();

            $.ajax({
                type: 'POST',
                data: `id=${id}`,
                url: url,
                dataType: "json",
                statusCode: {
                    404: function(){
                        Swal.fire('Error', 'Data tidak ditemukan', 'error');
                    }
                },
                beforeSend: function() {
                    $('#card_desc').show();
                    $('#spinner').show();
                    $('#category_desc').text('');
                },
                success: function(data){
                    $('#spinner').hide();
                    $('#category_desc').text(data.description);
                }
            });
        });
        
    });
</script>
@endpush

resources/views/pages/outbox/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card shadow-sm p-3">

                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4>Surat Keluar</h4>
                    </div>

                    <form action="{{ route('outbox.update', $data->id) }}" class="my-4" method="POST"
                          enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="reff">Nomor Surat</label>
                                    <input type="text" name="reff" class="form-control" value="{{ $data->reff }}"
                                           readonly>

                                    @error('reff')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="date">Tanggal Surat</label>
                                    @if ($editableDate)
                                    {{-- Jika tanggal bisa diedit --}}
                                    <input type="text" id="date" name="date"
                                           class="form-control datepicker @error('date') is-invalid @enderror"
                                           data-provide="datepicker"
                                           value="{{ old('date') ?? Carbon\Carbon::parse($data->date)->format('d-m-Y') }}">

                                    @error('date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror

                                    @else
                                    {{-- Jika tanggal tidak bisa diedit --}}
                                    <input type="text" id="date" name="date"
                                           class="form-control" readonly
                                           value="{{ Carbon\Carbon::parse($data->date)->format('d-m-Y') }}">
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="category_id">Kode Surat</label>
                                    <select name="category_id" id="category_id"
                                            class="form-control select2 @error('category_id') is-invalid @enderror">
                                        <option value="{{$data->category['id']}}">
                                            {{ $data->category['code']." - ".$data->category['name']}}
                                        </option>
                                    </select>

                                    @error('category_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="subject">Perihal</label>
                                    <input type="text" id="subject" name="subject"
                                           class="form-control @error('subject') is-invalid @enderror"
                                           value="{{ old('subject') ?? $data->subject }}">

                                    @error('subject')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="destination">Tujuan</label>
                                    <input type="text" id="destination" name="destination"
                                           class="form-control @error('destination') is-invalid @enderror"
                                           value="{{ old('destination') ?? $data->destination }}">

                                    @error('destination')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="document">Dokumen</label>
                                    @if ($data->document)
                                    <a href="{{ Storage::url($data->document) }}" target="_blank"
                                       class="btn btn-sm btn-light ml-2">Lihat Dokumen</a>
                                    @endif
                                    <input type="file" id="document" name="document"
                                           class="form-control @error('document') is-invalid @enderror"
                                           accept=".pdf" aria-describedby="fileHelpBlock">
                                    <small id="fileHelpBlock" class="form-text text-muted">
                                        Upload ulang hanya jika ingin mengganti dokumen.
                                    </small>
                                    @error('document')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div id="card_desc" class="card bg-light mt-2 mb-3" style="display: none">
                                    <div class="card-body">
                                        <div id="spinner" style="display: none">
                                            <div class="justify-content-center p-3 d-flex">
                                                <div class="dot-spin"></div>
                                            </div>
                                        </div>
                                        <div id="category_desc"></div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row mt-3">
                            <div class="col">
                                <button type="submit" class="btn btn-success px-3 mr-1">Simpan</button>
                                <a href="{{ route('outbox.index') }}" class="btn btn-light px-3">Kembali</a>
                                <button type="button" class="btn btn-outline-danger px-3"
                                        onclick="onDelete()">
                                    Hapus</button>
                            </div>
                        </div>
                    </form>

                    <form id="delete-item" action="{{ route('outbox.destroy', $data->id) }}" method="POST"
                          class="d-none">
                        @csrf
                        @method('DELETE')
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('script-after')
<script>
    $(document).ready(function(){

        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
            language: 'id',
            autoclose: true,
            todayHighlight: true,
            daysOfWeekHighlighted: [0],
        });

        $('#category_id').select2({
            ajax: {
                placeholder: '-- Pilih --',
                    dalay: 100,
                        url: '{{ route('api.category.populate') }}',
                        dataType: 'json',
                        type: 'POST',
                        data: function (params){
                        return {
                            q: params.term,
                            };
                        },
                        processResults: function (data) {
                        return {
                        results: data.items
                    };
                }
            }
        });

        $('#category_id').change(function(){
            const url = "{{ route('api.category.detail') }}";
            let id = $('#category_id').val();

            $.ajax({
                type: 'POST',
                data: `id=${id}`,
                url: url,
                dataType: "json",
                statusCode: {
                    404: function(){
                        Swal.fire('Error', 'Data tidak ditemukan', 'error');
                    }
                },
                beforeSend: function() {
                    $('#card_desc').show();
                    $('#spinner').show();
                    $('#category_desc').text('');
                },
                success: function(data){
                    $('#spinner').hide();
                    $('#category_desc').text(data.description);
                }
            });
        });

        onDelete = () => {
            swalDanger.fire({
                title: 'Anda yakin untuk menghapus?',
                text: 'Data yang telah dihapus tidak dapat dikembalikan!',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: `Hapus`,
                cancelButtonText: `Batal`,
                reverseButtons: true,
                focusConfirm: false,
                }).then((result) => {
                    if (result.isDenied) {
                        $('#delete-item').submit();
                    } 
                }
            )
        }
    });
</script>
@endpush

resources/views/pages/outbox/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card glass-effect p-3" style="background-color: transparent; border:none">

                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h3 class="text-white">Surat Keluar</h3>
                        <a href="{{ route('outbox.create') }}" class="btn btn-success px-4">Tambah Data</a>
                    </div>

                    @include('includes.alert')

                    <div class="bg-white rounded p-3 mt-3 ">
                        <div class="table-responsive mt-3">
                            <table id="resultTable" class="table">
                                <thead>
                                    <tr>
                                        <th>Nomor Surat</th>
                                        <th>Tanggal</th>
                                        <th>Kode Surat</th>
                                        <th>Perihal</th>
                                        <th>Tujuan</th>
                                        <th>Salinan</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('script-after')
<script>
    const dataTable = $('#resultTable').DataTable({
        processing: true,
        serverSide: true,
        ordering: true,
        scrollX: true,
        scroller: true,
        ajax: {
            url: '{!! url()->current() !!}'
        },
        columns: [
            { data : 'reff', name: 'reff' },
            { data : 'date', name: 'date', width: '80' },
            { data : 'category', name: 'category' },
            { data : 'subject', name: 'subject', width: '200' },
            { data : 'destination', name: 'destination', width: '200' },
            { data : 'document', name: 'document', className: 'text-center' },
            { data : 'action', name: 'action' },
        ],
        columnDefs: [
            { orderable: false, targets: 5 }
        ],
        order: [
            [1, 'desc'],
            [0, 'desc'],
        ]
    })
</script>
@endpush